version: 2.1

orbs:
  node: circleci/node@4.4.0

jobs:
  build:
    docker:
      - image: cimg/php:8.0.6
    steps:
      - checkout
      - run: make
  test:
    docker:
      - image: cimg/node:16.2.0
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run: make test

workflows:
  build_and_test:
    jobs: [build, test]
